version: "3"

services:
  nlp-server:
    build: .
    command: nlp-service 127.0.0.1:5678
  server:
    build: .
    depends_on:
      - nlp-server
    ports:
      - "6789:6789"
    volumes:
      - .:/app
    command: /wait nlp-server:5678 --strict --timeout 0 -- python -m arguequery.server
  client:
    build: .
    depends_on:
      - server
    volumes:
      - .:/app
    command: /wait server:6789 --strict --timeout 0 -- python -m arguequery.client
