version: "3"

services:
  nlp-service:
    build:
      context: .
      dockerfile: Dockerfile.nlp
    command:
      - nlp-service
      - ${ARGUEQUERY_NLP_HOST}:${ARGUEQUERY_NLP_PORT}
  retrieval-service:
    build: .
    ports:
      - "${ARGUEQUERY_RETRIEVAL_PORT}:${ARGUEQUERY_RETRIEVAL_PORT}"
    volumes:
      - .:/app
    command:
      - /wait
      - ${ARGUEQUERY_NLP_HOST}:${ARGUEQUERY_NLP_PORT}
      - --strict
      - --timeout=0
      - --
      - python
      - -m
      - arguequery
      - --retrieval-address
      - ${ARGUEQUERY_RETRIEVAL_HOST}:${ARGUEQUERY_RETRIEVAL_PORT}
      - --nlp-address
      - ${ARGUEQUERY_NLP_HOST}:${ARGUEQUERY_NLP_PORT}
  client:
    build: .
    depends_on:
      - retrieval-service
    volumes:
      - .:/app
    command:
      - /wait
      - ${ARGUEQUERY_RETRIEVAL_HOST}:${ARGUEQUERY_RETRIEVAL_PORT}
      - --strict
      - --timeout=0
      - --
      - python
      - -m
      - arguequery.client
      - --retrieval-address
      - ${ARGUEQUERY_RETRIEVAL_HOST}:${ARGUEQUERY_RETRIEVAL_PORT}
