# If true, only one thread will be used (which decreases performance)
debug = true
nlp_url = "127.0.0.1:5678"
retrieval_url = "127.0.0.1:6789"

[path]
glob_pattern = "*.json"
cases = "data/cases/english/microtexts-plain"
queries = "data/queries/english/microtexts-plain/all"
benchmark = "data/benchmark/microtexts"
results = "data/results"
ontology = "ontology.yml"

[nlp]
language = "en"
config = "default"
enforce_scheme_types = false
use_scheme_ontology = false  # only relevant if 'enforce_scheme_types = true'

[cbr]
mapping_algorithm = "MAPPING_ALGORITHM_ASTAR"
limit = 10
mac = true
fac = true
queue_limit = 10000
max_user_rank = 3

[export]
individual_results = false
aggregated_results = true
