# If true, only one thread will be used (which decreases performance)
debug = true
nlp_address = "127.0.0.1:5678"
retrieval_address = "127.0.0.1:6789"


[server]
scheme_ontology = "ontology.yml"
astar_queue_limit = 10000


[client]
[client.path]
cases = "data/cases/english/microtexts-plain"
case_graphs_pattern = "*.json"

queries = "data/queries/english/microtexts-plain/all"
query_graphs_pattern = "*.json"
query_texts_pattern = "*.txt"

benchmark_rankings = "data/benchmark/microtexts"
evaluation_output = "data/results"

[client.request]
language = "en"
nlp_config = "default"
enforce_scheme_types = false
use_scheme_ontology = false  # only relevant if 'enforce_scheme_types = true'
mapping_algorithm = "astar"
limit = 10
mac = true
fac = true

[client.evaluation]
individual_results = false
aggregated_results = true
max_user_rank = 3
