# If true, only one thread will be used (which decreases performance)
debug = true

[microservices]
nlp = "127.0.0.1:5678"
retrieval = "127.0.0.1:6789"

[path]
scheme_ontology = "ontology.yml"

cases = "data/cases/english/microtexts-plain"
case_graphs_pattern = "*.json"

queries = "data/queries/english/microtexts-plain/all"
query_graphs_pattern = "*.json"
query_texts_pattern = "*.txt"

benchmark_rankings = "data/benchmark/microtexts"
evaluation_output = "data/results"

[nlp]
language = "en"
config = "default"
enforce_scheme_types = false
use_scheme_ontology = false  # only relevant if 'enforce_scheme_types = true'

[cbr]
mapping_algorithm = "MAPPING_ALGORITHM_ASTAR"
limit = 10
mac = true
fac = true
queue_limit = 10000
max_user_rank = 3

[export]
individual_results = false
aggregated_results = true
