# If true, only one thread will be used (which decreases performance)
debug = false
nlp_url = "127.0.0.1:5678"

[path]
cases = "data/cases/english/microtexts-annotated"
queries = "data/queries/english/microtexts-annotated"
benchmark = "data/benchmark/microtexts"
results = "data/results"
ontology = "ontology.yml"

[cbr]
queue_limit = 10000
max_user_rank = 3

[export]
individual_results = false
aggregated_results = true
