# https://github.com/facebookresearch/hydra/issues/1376#issuecomment-1010247754
defaults:
  - retrieval_config
  - _self_
  - override hydra/launcher: joblib

hydra:
  sweeper:
    subdir: ${hydra.job.override_dirname}
    params:
      request.enforce_scheme_types: true, false
      request.use_scheme_ontology: true, false
