# https://github.com/facebookresearch/hydra/issues/1376#issuecomment-1010247754
defaults:
  - cbr
  - _self_
  - override hydra/launcher: joblib
# hydra:
#   sweeper:
#     subdir: ${hydra.job.override_dirname}
#     params:
#       retrieval.mac: true, false
#       retrieval.fac: true, false
#       retrieval.limit: 5, 10, 20
